name: MYCI

on: 
  push:
    branches: 
    - master
    paths:
    - src/*

jobs:
  job1-build:
    runs-on: ubuntu-latest
    container:
      image: node:8
    steps:
    - uses: actions/checkout@v1
    - run: 
        node -v
    
      
